#-------------------------------
# General Site Settings
# title: Zolan
# logo: logo.svg # You can add own logo.
# description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Ananya Verma
  image: my_image.jpg
  say-hello: Hello, I’m <strong>Ananya Verma</strong>
  bio: Robotics Developer with a penchant for Robot Perception and Navigation 🤖 , coding in Python and C++. I am passionate about Space Robotics, and like to explore the exciting intersection of robotics and space exploration 🚀. Additionally, I have an incurable addiction to books 📚 .

#-------------------------------
# Contact links
github: https://github.com/ananyaverma2 # Add your github handle
linkedin: https://www.linkedin.com/in/ananya-verma-a0b21b218/ # Add your linkedin handle
email: https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=ananyaverma2196@gmail.com # Add your email handle
# # instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
# instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
# instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
